services:
  database:
    image: mysql
    volumes:
      - "./.mysql-data/:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: admin123
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
  init-db:
    image: mysql:latest
    container_name: init-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: admin123
    volumes:
      - "./init-scripts:/docker-entrypoint-initdb.d"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    depends_on:
      - database
  web:
    build: .
    ports:
      - "8080:8080"