services:
  database:
    image: mysql
    volumes:
      - "./.mysql-data/:/var/lib/mysql"
      - "./init-scripts:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: admin123
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
  web:
    build: .
    ports:
      - "8080:8080"